"""create owners table

Revision ID: 24695d2d094e
Revises: ffdc0a98111c
Create Date: 2021-07-28 02:15:21.972125

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '24695d2d094e'
down_revision = 'ffdc0a98111c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('services',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('billing_code', sa.Integer(), nullable=False),
    sa.Column('cpt_code', sa.String(length=10), nullable=True),
    sa.Column('service_description', sa.String(length=140), nullable=False),
    sa.Column('list_price', sa.NUMERIC(precision=9, scale=2), nullable=True),
    sa.Column('discounted_price', sa.NUMERIC(precision=9, scale=2), nullable=True),
    sa.Column('domain', sa.String(length=20), nullable=True),
    sa.Column('subdomain', sa.String(length=20), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('collections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=40), nullable=False),
    sa.Column('service_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['service_id'], ['services.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('users', sa.Column('is_admin', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_admin')
    op.drop_table('collections')
    op.drop_table('services')
    # ### end Alembic commands ###
