"""add service_collections table

Revision ID: a05389822a43
Revises: 46f39fda57bc
Create Date: 2021-08-01 14:06:26.834440

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a05389822a43'
down_revision = '46f39fda57bc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('service_collections',
    sa.Column('service_id', sa.Integer(), nullable=False),
    sa.Column('collection_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['collection_id'], ['collections.id'], ),
    sa.ForeignKeyConstraint(['service_id'], ['services.id'], ),
    sa.PrimaryKeyConstraint('service_id', 'collection_id')
    )
    op.drop_constraint('collections_service_id_fkey', 'collections', type_='foreignkey')
    op.drop_column('collections', 'service_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('collections', sa.Column('service_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('collections_service_id_fkey', 'collections', 'services', ['service_id'], ['id'])
    op.drop_table('service_collections')
    # ### end Alembic commands ###
