"""hospitals

Revision ID: 3bedda1f8855
Revises: 24695d2d094e
Create Date: 2021-07-28 14:50:40.045151

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3bedda1f8855'
down_revision = '24695d2d094e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hospitals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=30), nullable=False),
    sa.Column('state', sa.String(length=2), nullable=False),
    sa.Column('zip', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.add_column('services', sa.Column('hospital_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'services', 'hospitals', ['hospital_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'services', type_='foreignkey')
    op.drop_column('services', 'hospital_id')
    op.drop_table('hospitals')
    # ### end Alembic commands ###
